version: '3'

services:
  broker-service:
    build:
      context: broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8082:8082"
    deploy:
      mode: replicated
      replicas: 1
